### ISSUE TITLE
Saving sortable error

### ISSUE THREAD

**Issue by Mariano89** [bolshakov/activeadmin_sortable_table#23]
When attempting to sort via drag and drop, error in console shows:
`POST http://localhost:3001/admin/press_articles 422 (Unprocessable Entity)`
`Saving sortable error`
Move to top works perfectly fine.
I'm using Rails 5 api only. The only difference in setup may be that my models inherit from ApplicationRecord rather than ActiveRecord::Base. Regardless, this means application_record inherits from ActiveRecord::Base so it shouldn't cause an issue.

Any thoughts? Thanks in advanced.

**Comment by bolshakov** [comment]
@Mariano89 does it look like missing CSRF token? https://github.com/bolshakov/activeadmin_sortable_table/issues/20

**Comment by bolshakov** [comment]
I'd also suggest checking if the model has validation that fails.

**Comment by Mariano89** [comment]
@bolshakov Thanks so much for the quick response! The CSRF token was my issue. Everything is working great now! Thanks again.

**Comment by bolshakov** [comment]
@Mariano89 You're welcome!
